# Generated by Django 4.1.7 on 2023-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noOfCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('stupid', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('dumb', models.IntegerField(default=0)),
            ],
        ),
    ]
